In [2]:
# Imports libraries and sets up database connection

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nbformat
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg2://postgres:Lovebug7160!@localhost:5432/postgres')

In [3]:
# Imports mh_care_cdc dataset from PostgreSQL and prints first 5 rows to ensure proper transfer

mh_care_df = pd.read_sql('mh_care_cdc', con=engine)
mh_care_df.head()


# Renames column values to ensure better readability when creating tables and figures
new_names = {
    'With disability':'Has disability',
    'Without disability':'No disability',
    "Bachelor's degree or higher":"Bachelor's degree +",
    'High school diploma or GED':'Diploma/GED',
    'Less than high school diploma':'No HS diploma',
    "Some college/Associate's degree":"College/Associate's",
    'Cis-gender female':'Female',
    'Cis-gender male':'Male',
    'Did not experience symptoms of anxiety/depression in the past 4 weeks':'No anxiety/depression symptoms',
    'Experienced symptoms of anxiety/depression in past 4 weeks':'Anxiety/depression',
    'Non-Hispanic Asian, single race':'Asian',
    'Non-Hispanic Black, single race':'Black',
    'Non-Hispanic White, single race':'White',
    'Non-Hispanic, other races and multiple races':'Other/Multiple',
    'Alaska':'AK',
    'Alabama':'AL',
    'Arkansas':'AR',
    'Arizona':'AZ',
    'California':'CA',
    'Colorado':'CO',
    'Connecticut':'CT',
    'District of Columbia':'DC',
    'Delaware':'DE',
    'Florida':'FL',
    'Georgia':'GA',
    'Hawaii':'HI',
    'Iowa':'IA',
    'Idaho':'ID',
    'Illinois':'IL',
    'Indiana':'IN',
    'Kansas':'KS',
    'Kentucky':'KY',
    'Louisiana':'LA',
    'Massachusetts':'MA',
    'Maryland':'MD',
    'Maine':'ME',
    'Michigan':'MI',
    'Minnesota':'MN',
    'Missouri':'MO',
    'Mississippi':'MS',
    'Montana':'MT',
    'North Carolina':'NC',
    'North Dakota':'ND',
    'Nebraska':'NE',
    'New Hampshire':'NH',
    'New Jersey':'NJ',
    'New Mexico':'NM',
    'Nevada':'NV',
    'New York':'NY',
    'Ohio':'OH',
    'Oklahoma':'OK',
    'Oregon':'OR',
    'Pennsylvania':'PA',
    'Rhode Island':'RI',
    'South Carolina':'SC',
    'South Dakota':'SD',
    'Tennessee':'TN',
    'Texas':'TX',
    'Utah':'UT',
    'Virginia':'VA',
    'Vermont':'VT',
    'Washington':'WA',
    'Wisconsin':'WI',
    'West VA':'WV',
    'Wyoming':'WY'
}

new_ind = {
    'Took Prescription Medication for Mental Health And/Or Received Counseling or Therapy, Last 4 Weeks':'Took Prescription and/or Received Counseling/Therapy',
    'Needed Counseling or Therapy But Did Not Get It, Last 4 Weeks':'Needed Counseling/Therapy but Did Not Get It',
    'Received Counseling or Therapy, Last 4 Weeks':'Received Counseling/Therapy',
    'Took Prescription Medication for Mental Health, Last 4 Weeks':'Took Prescription Medication for Mental Health'
}

#Replaces long names with shortened versions
mh_care_df['subgroup'] = mh_care_df['subgroup'].str.replace(new_names)
mh_care_df['indicator'] = mh_care_df['indicator'].str.replace(new_ind)
mh_care_df.head()

,indicator,demo_group,subgroup,time_period_label,value,low_ci,high_ci,id,year
0,Took Prescription Medication for Mental Health,By State,IA,"Aug 19 - Aug 31, 2020",23.1,19.9,26.5,51,2020
1,Received Counseling/Therapy,By State,MT,"Aug 19 - Aug 31, 2020",9.2,7.1,11.7,134,2020
2,Needed Counseling/Therapy but Did Not Get It,By State,AL,"Aug 19 - Aug 31, 2020",8.4,6.5,10.6,253,2020
3,Received Counseling/Therapy,By Sex,Male,"Sep 2 - Sep 14, 2020",7.0,6.5,7.5,384,2020
4,Received Counseling/Therapy,By State,DE,"Sep 2 - Sep 14, 2020",9.3,6.5,12.8,404,2020

In [4]:
# Provides summary of the mh_care_df DataFrame, including data types and non-null counts

mh_care_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9914 entries, 0 to 9913
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   indicator          9914 non-null   str
 1   demo_group         9914 non-null   str
 2   subgroup           9914 non-null   str
 3   time_period_label  9914 non-null   str
 4   value              9914 non-null   float64
 5   low_ci             9914 non-null   float64
 6   high_ci            9914 non-null   float64
 7   id                 9914 non-null   int64
 8   year               9914 non-null   int64
dtypes: float64(3), int64(2), str(4)
memory usage: 697.2 KB

In [6]:
mh_care_nostate = mh_care_df[mh_care_df['demo_group']!='By State']
mh_care_nostate

,indicator,demo_group,subgroup,time_period_label,value,low_ci,high_ci,id,year
3,Received Counseling/Therapy,By Sex,Male,"Sep 2 - Sep 14, 2020",7.0,6.5,7.5,384,2020
5,Received Counseling/Therapy,By Education,Less than a high school diploma,"Sep 16 - Sep 28, 2020",8.5,6.4,11.0,680,2020
6,Needed Counseling/Therapy but Did Not Get It,By Age,18 - 29 years,"Sep 16 - Sep 28, 2020",18.5,17.1,20.0,806,2020
12,Took Prescription Medication for Mental Health,By Sex,Male,"Jan 6 - Jan 18, 2021",14.8,13.9,15.8,2527,2021
17,Received Counseling/Therapy,By Age,60 - 69 years,"Feb 17 - Mar 1, 2021",5.8,5.2,6.5,3472,2021
...,...,...,...,...,...,...,...,...,...
9858,Needed Counseling/Therapy but Did Not Get It,By Education,Diploma/GED,"Apr 27 - May 9, 2022",9.1,7.7,10.5,10349,2022
9859,Needed Counseling/Therapy but Did Not Get It,By Education,College/Associate's,"Apr 27 - May 9, 2022",15.1,14.0,16.2,10350,2022
9860,Needed Counseling/Therapy but Did Not Get It,By Education,Bachelor's degree +,"Apr 27 - May 9, 2022",10.4,9.8,11.0,10351,2022
9861,Needed Counseling/Therapy but Did Not Get It,By Disability status,Has disability,"Apr 27 - May 9, 2022",25.3,23.3,27.4,10352,2022
9862,Needed Counseling/Therapy but Did Not Get It,By Disability status,No disability,"Apr 27 - May 9, 2022",9.1,8.5,9.7,10353,2022

In [7]:
mh_care_max = mh_care_df.groupby(['indicator','subgroup','time_period_label'])[['value','low_ci','high_ci']].apply(lambda grp: grp.nlargest(n=10, columns='value').mean())
mh_care_max.sort_values(by=['value'],ascending=False)

                                                                                             value  \
indicator                                          subgroup           time_period_label
Took Prescription and/or Received Counseling/Th... Transgender        Aug 4 - Aug 16, 2021    62.9
                                                                      Jan 26 - Feb 7, 2022    60.1
                                                                      Apr 27 - May 9, 2022    57.3
                                                                      Jul 21 - Aug 2, 2021    56.6
                                                                      Sep 15 - Sep 27, 2021   56.0
...                                                                                            ...
Needed Counseling/Therapy but Did Not Get It       80 years and above Aug 4 - Aug 16, 2021     2.1
Received Counseling/Therapy                        80 years and above Apr 27 - May 9, 2022     2.0
Needed Counseling/Therapy but Did Not Get It       80 years and above Jun 23 - Jul 5, 2021     1.8
                                                                      Aug 19 - Aug 31, 2020    1.4
Received Counseling/Therapy                        80 years and above Feb 17 - Mar 1, 2021     1.4

                                                                                             low_ci  \
indicator                                          subgroup           time_period_label
Took Prescription and/or Received Counseling/Th... Transgender        Aug 4 - Aug 16, 2021     53.2
                                                                      Jan 26 - Feb 7, 2022     49.2
                                                                      Apr 27 - May 9, 2022     44.0
                                                                      Jul 21 - Aug 2, 2021     43.9
                                                                      Sep 15 - Sep 27, 2021    45.7
...                                                                                             ...
Needed Counseling/Therapy but Did Not Get It       80 years and above Aug 4 - Aug 16, 2021      1.2
Received Counseling/Therapy                        80 years and above Apr 27 - May 9, 2022      1.3
Needed Counseling/Therapy but Did Not Get It       80 years and above Jun 23 - Jul 5, 2021      0.8
                                                                      Aug 19 - Aug 31, 2020     0.9
Received Counseling/Therapy                        80 years and above Feb 17 - Mar 1, 2021      0.9

                                                                                             high_ci
indicator                                          subgroup           time_period_label
Took Prescription and/or Received Counseling/Th... Transgender        Aug 4 - Aug 16, 2021      71.9
                                                                      Jan 26 - Feb 7, 2022      70.2
                                                                      Apr 27 - May 9, 2022      69.8
                                                                      Jul 21 - Aug 2, 2021      68.7
                                                                      Sep 15 - Sep 27, 2021     65.9
...                                                                                              ...
Needed Counseling/Therapy but Did Not Get It       80 years and above Aug 4 - Aug 16, 2021       3.2
Received Counseling/Therapy                        80 years and above Apr 27 - May 9, 2022       3.0
Needed Counseling/Therapy but Did Not Get It       80 years and above Jun 23 - Jul 5, 2021       3.5
                                                                      Aug 19 - Aug 31, 2020      2.0
Received Counseling/Therapy                        80 years and above Feb 17 - Mar 1, 2021       2.1

[9818 rows x 3 columns]

In [8]:
mh_care_top = mh_care_nostate.groupby(['indicator','demo_group','subgroup'])[['value','low_ci','high_ci']].mean()
mh_care_top.reset_index()

,indicator,demo_group,subgroup,value,low_ci,high_ci
0,Needed Counseling/Therapy but Did Not Get It,By Age,18 - 29 years,19.848485,17.878788,21.936364
1,Needed Counseling/Therapy but Did Not Get It,By Age,30 - 39 years,15.566667,14.321212,16.896970
2,Needed Counseling/Therapy but Did Not Get It,By Age,40 - 49 years,11.845455,10.800000,12.951515
3,Needed Counseling/Therapy but Did Not Get It,By Age,50 - 59 years,9.148485,8.212121,10.169697
4,Needed Counseling/Therapy but Did Not Get It,By Age,60 - 69 years,5.775758,5.087879,6.539394
...,...,...,...,...,...,...
111,Took Prescription and/or Received Counseling/T...,By Sex,Male,18.493939,17.581818,19.418182
112,Took Prescription and/or Received Counseling/T...,By Sexual orientation,Bisexual,46.366667,42.333333,50.466667
113,Took Prescription and/or Received Counseling/T...,By Sexual orientation,Gay or lesbian,39.125000,34.900000,43.483333
114,Took Prescription and/or Received Counseling/T...,By Sexual orientation,Straight,24.258333,23.591667,24.908333
115,Took Prescription and/or Received Counseling/T...,National Estimate,United States,24.836364,24.206061,25.478788

In [9]:
mh_care_highest= mh_care_top.groupby(level='indicator')['value'].nlargest(312).reset_index(level=0, drop=True).reset_index()
mh_care_highest.sort_values(by='value', ascending=False).head(312)

,indicator,demo_group,subgroup,value
87,Took Prescription and/or Received Counseling/T...,By Gender identity,Transgender,54.458333
88,Took Prescription and/or Received Counseling/T...,By Disability status,Has disability,46.444444
89,Took Prescription and/or Received Counseling/T...,By Sexual orientation,Bisexual,46.366667
58,Took Prescription Medication for Mental Health,By Gender identity,Transgender,44.200000
59,Took Prescription Medication for Mental Health,By Disability status,Has disability,42.727778
...,...,...,...,...
56,Received Counseling/Therapy,By Age,70 - 79 years,4.169697
57,Received Counseling/Therapy,By Age,80 years and above,3.648148
26,Needed Counseling/Therapy but Did Not Get It,By Presence of Symptoms of Anxiety/Depression,No anxiety/depression symptoms,3.418182
27,Needed Counseling/Therapy but Did Not Get It,By Age,80 years and above,3.403846
28,Needed Counseling/Therapy but Did Not Get It,By Age,70 - 79 years,3.263636

In [10]:
age_demo = mh_care_highest[mh_care_highest['demo_group'] == 'By Age']
disability_demo = mh_care_highest[mh_care_highest['demo_group'] == 'By Disability status']
edu_demo = mh_care_highest[mh_care_highest['demo_group'] == 'By Education']
gender_demo = mh_care_highest[mh_care_highest['demo_group'] == 'By Gender identity']
sex_demo = mh_care_highest[mh_care_highest['demo_group'] == 'By Sex']
orient_demo = mh_care_highest[mh_care_highest['demo_group'] == 'By Sexual orientation']
race_demo = mh_care_highest[mh_care_highest['demo_group'] == 'By Race/Hispanic ethnicity']

In [11]:
# Creates Figure
heat = go.Figure()

#Adds traces for each subgroup

heat.add_trace(
    go.Heatmap(
        z=age_demo.value, 
        x=age_demo.subgroup, 
        y=age_demo.indicator, 
        colorscale='Viridis', 
        name='Age Demographics'))

heat.add_trace(
    go.Heatmap(
        z=disability_demo.value, 
        x=disability_demo.subgroup, 
        y=disability_demo.indicator, 
        colorscale='Plasma', 
        name='Pesence of Disability', 
        visible=False))

heat.add_trace(
    go.Heatmap(
        z=edu_demo.value,
        x=edu_demo.subgroup,
        y=edu_demo.indicator,
        colorscale='darkmint',
        visible=False
    )
)

heat.add_trace(
    go.Heatmap(
        z=gender_demo.value,
        x=gender_demo.subgroup,
        y=gender_demo.indicator,
        colorscale='brwnyl',
        name='Gender Identity',
        visible=False
    )
)

heat.add_trace(
    go.Heatmap(
        z=sex_demo.value,
        x=sex_demo.subgroup,
        y=sex_demo.indicator,
        colorscale='darkmint',
        visible=False
    )
)
heat.add_trace(
    go.Heatmap(
        z=orient_demo.value,
        x=orient_demo.subgroup,
        y=orient_demo.indicator,
        colorscale='haline',
        visible=False
    )
)

heat.add_trace(
    go.Heatmap(
        z=race_demo.value,
        x=race_demo.subgroup,
        y=race_demo.indicator,
        colorscale='agsunset',
        visible=False
    )
)

#Create Dropdown Menu
buttons = []
for i, group in enumerate(['Age', 'Disability Status', 'Education', 'Gender Identity', 'Sex', 'Sexual Orientation', 'Race']):
    # Define visibility: True for selected group, False for others
    visibility = [False] * 7
    visibility[i] = True
    
    button = dict(
        label=group,
        method='restyle',
        args=[{'visible': visibility}]
    )
    buttons.append(button)

# 4. Update layout with buttons
heat.update_layout(
    updatemenus=[dict(
        active=0,
        buttons=buttons,
        direction='down',
        x=0.1, y=1.15
    )],
    title="Mental Health Indicators by Demographic Group"
)

heat.show()

heat.write_html('/workspaces/Mental-Health-Dashboard/notebooks/images/mh_care_heatmap.html')

In [14]:
# Provides statistical summary of the mh_care_df DataFrame, including count, mean, std, min, 25th percentile, 50th percentile, 75th percentile, and max for each numeric column

mh_care_df.describe()

             value       low_ci      high_ci            id         year
count  9914.000000  9914.000000  9914.000000   9914.000000  9914.000000
mean     17.450736    14.771565    20.475661   5143.996873  2020.900242
std       8.270565     7.659396     9.052521   3005.819089     0.642201
min       1.400000     0.800000     2.000000      1.000000  2020.000000
25%      10.300000     8.000000    12.900000   2499.250000  2020.000000
50%      16.200000    13.900000    19.200000   5142.500000  2021.000000
75%      24.000000    20.800000    27.400000   7715.750000  2021.000000
max      62.900000    53.200000    71.900000  10404.000000  2022.000000

In [32]:
# Develops a pivot table using indicator and state variables

mhcare_state_pivot = mh_care_df[mh_care_df['demo_group']=='By State'].pivot_table(
    values=['value','low_ci','high_ci'],
    index=['year','indicator','subgroup'],
    aggfunc='median',
    margins=False
)
mhcare_state_pivot = mhcare_state_pivot.reset_index()  ## Necessary to allow the states to be classified as a column in the chloropleth map generation
mhcare_state_pivot

,year,indicator,subgroup,high_ci,low_ci,value
0,2020,Needed Counseling/Therapy but Did Not Get It,AK,13.6,8.8,11.3
1,2020,Needed Counseling/Therapy but Did Not Get It,AL,13.0,7.6,9.9
2,2020,Needed Counseling/Therapy but Did Not Get It,AR,13.7,7.8,10.5
3,2020,Needed Counseling/Therapy but Did Not Get It,AZ,13.8,9.5,11.4
4,2020,Needed Counseling/Therapy but Did Not Get It,CA,15.0,10.9,13.1
...,...,...,...,...,...,...
607,2022,Took Prescription and/or Received Counseling/T...,VT,34.2,25.2,29.5
608,2022,Took Prescription and/or Received Counseling/T...,WA,29.6,25.0,27.3
609,2022,Took Prescription and/or Received Counseling/T...,WI,31.7,23.8,27.6
610,2022,Took Prescription and/or Received Counseling/T...,WV,43.2,30.6,36.8
611,2022,Took Prescription and/or Received Counseling/T...,WY,27.2,18.3,22.9

In [36]:
# Plots indicators stratified by state (choropleth map) using plotly


# Returns the list of indicators 
indicators = mhcare_state_pivot['indicator'].unique()
indicators


# Builds one choropleth trace per indicator 
fig = go.Figure()

for i, ind in enumerate(indicators):
    df_ind = mhcare_state_pivot[mhcare_state_pivot['indicator'] == ind]

    fig.add_trace(
        go.Choropleth(
            locations=df_ind['subgroup'],
            z=df_ind['value'].astype(float),
            locationmode='USA-states',
            colorscale='Greens',
            colorbar_title='Value',
            visible=True if i == 0 else False,
            name = ind,
            text=(
                'State: ' + df_ind['subgroup'] +
                '<br>Value: '+df_ind['value'].round(2).astype(str) +
                '<br>Low CI: '+df_ind['low_ci'].round(2).astype(str) +
                '<br>High CI: '+ df_ind['high_ci'].round(2).astype(str)
            ),
            hoverinfo='text+z'
        )
    )

# Creates a dropdown menu to toggle between indicators 

buttons = []
for i, ind in enumerate(indicators):
    visible = [False] * len(indicators)
    visible[i] = True

    buttons.append(
        dict(
            label=ind,
            method='update',
            args=[
                {'visible': visible},
                {'title': f'{ind} by State'}
            ]
        )
    )

# Attaches the dropdown to the figure

fig.update_layout(
    updatemenus=[
        dict(
            active=0,
            buttons=buttons,
            x=0.0,
            y=1.15,
            xanchor='left',
            yanchor='top'
        )
    ],
    title_text=f'{indicators[0]} by State',
    geo_scope='usa'
)

fig.write_html('/workspaces/Mental-Health-Dashboard/notebooks/images/mh_care_chloropleth.html')

fig